config/routes.rb
Rails.application.routes.draw do
  resources :notas do
    member do
      post "cerrar"
      get "cierre"
    end
    collection do
      get "top10"
      get "recuperacion"
      get "download"
    end
  end
  resources :alumnos do
    member do
      get "notas"
    end
  end
  resources :cursos do
    member do
      get "notas"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 
      devise_scope :admin do
        post "register", to: "auth#register"
        post "login", to: "auth#login"
      end
    end
  end
end

app/models/alumno.rb
class Alumno < ApplicationRecord
    has_many :alumnos_cursos, dependent: :destroy
    has_many :cursos, through: :alumnos_cursos

    has_many :notas, :dependent => :destroy

    paginates_per 7
end

app/controllers/alumnos_controller.rb
class AlumnosController < ApplicationController
  before_action :set_alumno, only: %i[ show edit update destroy notas ]


  # GET /alumnos/:id(alumno)/notas
  def notas 
    if params[:curso] == "" || !params[:curso] 
      @notas = @alumno.notas
    else
      @notas = @alumno.notas.where('curso_id' => params[:curso])

      if @notas.length > 0
      
        @maximo_bimestre = @notas.maximum('bimestre')
        @sumatoria_notas = 0
  
        @notas.each do |nota|
          @sumatoria_notas = @sumatoria_notas + nota.total 
        end
  
        @sumatoria_notas = @sumatoria_notas / @maximo_bimestre
      end
      
    end
    # 
  end



  # GET /alumnos or /alumnos.json
  def index
    @alumnos = Alumno.where("nombre like ?", "%#{params[:buscar]}%").page params[:page]
  end

  # GET /alumnos/1 or /alumnos/1.json
  def show
  end

  # GET /alumnos/new
  def new
    @alumno = Alumno.new
  end

  # GET /alumnos/1/edit
  def edit
  end

  # POST /alumnos or /alumnos.json
  def create
    @alumno = Alumno.new(alumno_params)

    respond_to do |format|
      if @alumno.save
        format.html { redirect_to alumno_url(@alumno), notice: "Alumno was successfully created." }
        format.json { render :show, status: :created, location: @alumno }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alumnos/1 or /alumnos/1.json
  def update
    respond_to do |format|
      if @alumno.update(alumno_params)
        format.html { redirect_to alumno_url(@alumno), notice: "Alumno was successfully updated." }
        format.json { render :show, status: :ok, location: @alumno }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @alumno.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alumnos/1 or /alumnos/1.json
  def destroy
    @alumno.destroy

    respond_to do |format|
      format.html { redirect_to alumnos_url, notice: "Alumno was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alumno
      @alumno = Alumno.find(params[:id])
      @cursos = @alumno.cursos.all
    end

    # Calcula priomedio

    # Only allow a list of trusted parameters through.
    def alumno_params
      puts 'ERRRRRRRRROR'
      puts params
      puts 'ERRRRRRRRROR'
      params.require(:alumno).permit(:nombre, :grado, :edad, :curso_ids=>[])
    end
end

app/helpers/alumnos_helper.rb
module AlumnosHelper
end

app/views/alumnos/_alumno.html.erb
<div id="<%= dom_id alumno %>">
  <p>
    <strong>Nombre:</strong>
    <%= alumno.nombre %>
  </p>

  <p>
    <strong>Grado:</strong>
    <%= alumno.grado %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= alumno.edad %>
  </p>

</div>

app/views/alumnos/_alumnosCurso.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Cursos</th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |curso| %>
    <tr>
      <th scope="row"><%= curso.nombre%></th>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/alumnos/_form.html.erb
<%= simple_form_for(@alumno) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :grado %>
    <%= f.input :edad %>
    <%= f.association :cursos, label: 'Añadir Cursos', label_method: :nombre %>
  </div>

  <div class="form-actions">
     <%= f.button :submit, "Crear Alumno", :class=>"btn btn-dark", :style=>"margin-top: 10px"%>
  </div>
<% end %>

app/views/alumnos/edit.html.erb
<h1>Editing alumno</h1>

<%= render "form", alumno: @alumno %>

<br>

<div>
  <%= link_to "Show this alumno", @alumno %> |
  <%= link_to "Back to alumnos", alumnos_path %>
</div>

app/views/alumnos/index.html.erb
<h1>Alumnos</h1>

<form class="form-inline" action="/alumnos" method="get">
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Busqueda</label>
    <input type="text" class="form-control" id="buscar" placeholder="Ingrese nombre a buscar" name="buscar" value="<%= params[:buscar] %>">
  </div>
  <button type="submit" class="btn btn-dark">Buscar</button>
  <a href="/alumnos" class="btn btn-dark">Limpiar</a>
</form>
<hr>

<div id="alumnos">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Grado</th>
      <th scope="col">Edad</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
  <% @alumnos.each do |alumno| %>
    <tr>
      <th scope="row"><%= alumno.nombre%></th>
      <td><%= alumno.grado%></td>
      <td><%= alumno.edad%></td>
      <td class="action-container">
      <%= link_to alumno, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-user'></i>
          <p>Ver</p>
        </div>
      <% end %>
      <%= link_to edit_alumno_path(alumno), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <%= link_to notas_alumno_path(alumno), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-notepad'></i>
          <p>Notas</p>
        </div>
      <% end %>
      <%=button_to alumno, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<%= link_to "Nuevo alumno", new_alumno_path, :class=>"btn btn-dark"  %><br> <br> <br>


<%= paginate @alumnos, theme: 'bootstrap-5',
    pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block" %>
    <hr>

app/views/alumnos/new.html.erb
<h1>New alumno</h1>

<%= render "form", alumno: @alumno %>

<br>

<div>
  <%= link_to "Lista de alumnos", alumnos_path, :class=>"btn btn-warning"   %>
</div>

app/views/alumnos/notas.html.erb
<h4 style="margin-top: 20px;">Notas de <%= @alumno.nombre %></h4>

<%= form_with url: "", method: :get do |form| %>
  <%= form.collection_select :curso, @cursos, :id, :nombre, { selected: params[:curso], :include_blank => 'Todos los cursos'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
<% end %>

<% if @notas.length > 0 %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Curso</th>
      <th scope="col">Nota</th>
      <th scope="col">Bimestre</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
  <% @notas.each do |nota| %>
    <tr>
      <th scope="row"><%= nota.curso.nombre%></th>
      <td><%= nota.total%> pts</td>
      <td><%= nota.bimestre%></td>
      <td class="action-container">
      <%= link_to edit_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
       <% if nota.abierto? %>
      <%= link_to cierre_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bx-stop'></i>
          <p>Cerrar</p>
        </div>
      <% end %>  
      <% end %>
      <%=button_to nota, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
  <h4 style="margin: 20px 0px;">No hay notas disponibles</h4>
<% end %>

<%# Muestra el promedio %>
<div class="promedio">
<h5>Promedio:</h5>
<h5><%=number_with_precision(@sumatoria_notas, precision: 2)%> pts</h5>
</div>


<%= link_to "Crear Nota", new_nota_path(:alumno =>@alumno.id , :curso =>params[:curso]), :class=>"btn btn-dark"  %>

app/views/alumnos/show.html.erb
<h5>Curso</h5>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Nombre</th>
      <th scope="col">Grado</th>
      <th scope="col">Edad</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row"><%= @alumno.nombre%></th>
      <td><%= @alumno.grado%></td>
      <td><%= @alumno.edad%></td>
      <td class="action-container">
      <%= link_to edit_alumno_path(@alumno), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <%= link_to notas_alumno_path(@alumno), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-notepad'></i>
          <p>Notas</p>
        </div>
      <% end %>
      <%= button_to @alumno, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>

<h5>Cursos asignados</h5>
<%= render 'alumnosCurso' %>

<div>
  <%= link_to "Lista de alumnos", alumnos_path, :class=>"btn btn-warning" %>
</div>