config/routes.rb
Rails.application.routes.draw do
  resources :notas do
    member do
      post "cerrar"
      get "cierre"
    end
    collection do
      get "top10"
      get "recuperacion"
      get "download"
    end
  end
  resources :alumnos do
    member do
      get "notas"
    end
  end
  resources :cursos do
    member do
      get "notas"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 
      devise_scope :admin do
        post "register", to: "auth#register"
        post "login", to: "auth#login"
      end
    end
  end
end

app/models/curso.rb
class Curso < ApplicationRecord
    has_many :alumnos_cursos, dependent: :destroy
    has_many :alumnos, through: :alumnos_cursos

    has_many :notas, :dependent => :destroy

    paginates_per 7


    validates :nombre, presence: true
    validates :profesor, presence: true
end

app/controllers/cursos_controller.rb
class CursosController < ApplicationController
  before_action :set_curso, only: %i[ show edit update destroy notas cierre]

 # GET /alumnos/:id(alumno)/notas
  def notas 
    if params[:alumno] == "" || !params[:alumno] 
      @notas = @curso.notas
    else
      @notas = @curso.notas.where('alumno_id' => params[:alumno])

      if @notas.length > 0
      
        @maximo_bimestre = @notas.maximum('bimestre')
        @sumatoria_notas = 0
  
        @notas.each do |nota|
          @sumatoria_notas = @sumatoria_notas + nota.total 
        end
  
        @sumatoria_notas = @sumatoria_notas / @maximo_bimestre
      end
      
    end
    # 
  end
  

  # GET /cursos or /cursos.json
  def index
    @cursos = Curso.where("nombre like ?", "%#{params[:buscar]}%").page params[:page]
  end

  # GET /cursos/1 or /cursos/1.json
  def show
  end

  # GET /cursos/new
  def new
    @curso = Curso.new
  end

  # GET /cursos/1/edit
  def edit
  end

  # POST /cursos or /cursos.json
  def create
    @curso = Curso.new(curso_params)

    respond_to do |format|
      if @curso.save
        format.html { redirect_to curso_url(@curso), notice: "Curso was successfully created." }
        format.json { render :show, status: :created, location: @curso }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cursos/1 or /cursos/1.json
  def update
    respond_to do |format|
      if @curso.update(curso_params)
        format.html { redirect_to curso_url(@curso), notice: "Curso was successfully updated." }
        format.json { render :show, status: :ok, location: @curso }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @curso.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cursos/1 or /cursos/1.json
  def destroy
    @curso.destroy

    respond_to do |format|
      format.html { redirect_to cursos_url, notice: "Curso was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_curso
      @curso = Curso.find(params[:id])
      @alumnos = @curso.alumnos.all
    end

    # Only allow a list of trusted parameters through.
    def curso_params
      params.require(:curso).permit(:nombre, :profesor, :alumno_ids=>[])
    end
end

app/helpers/cursos_helper.rb
module CursosHelper
end

app/views/cursos/_curso.html.erb
<div id="<%= dom_id curso %>">
  <p>
    <strong>Nombre:</strong>
    <%= curso.nombre %>
  </p>

  <p>
    <strong>Profesor:</strong>
    <%= curso.profesor %>
  </p>

</div>

app/views/cursos/_cursoAlumnos.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
    </tr>
  </thead>

  <tbody>
    <% @alumnos.each do |alumno| %>
    <tr>
      <th scope="row"><%= alumno.nombre%></th>
    </tr>
      <% end %>
  </tbody>
</table>

app/views/cursos/_form.html.erb
<%= simple_form_for(@curso) do |f| %>

  <div class="form-inputs">
    <%= f.input :nombre,  label: 'Nombre del curso', error: 'El nombre es necesario' %>
    <%= f.input :profesor,  label: 'Nombre del profesor', error: 'El nombre es necesario' %>
    <%= f.association :alumnos, label: 'Añadir Alumnos', label_method: :nombre %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Crear curso", :class=>"btn btn-dark", :style=>"margin-top: 10px"%>
  </div>
<% end %>

app/views/cursos/edit.html.erb
<h1>Editing curso</h1>

<%= render "form", curso: @curso %>

<br>

<div>
  <%= link_to "Show this curso", @curso, :class=>"btn btn-warning"   %> |
  <%= link_to "Back to cursos", cursos_path, :class=>"btn btn-warning"   %>
</div>

app/views/cursos/index.html.erb
<h1>Cursos</h1>


<form class="form-inline" action="/cursos" method="get">
  <div class="form-group mx-sm-3 mb-2">
    <label for="inputPassword2" class="sr-only">Busqueda</label>
    <input type="text" class="form-control" id="buscar" placeholder="Ingrese nombre a buscar" name="buscar" value="<%= params[:buscar] %>">
  </div>
  <button type="submit" class="btn btn-dark">Buscar</button>
  <a href="/cursos" class="btn btn-dark">Limpiar</a>
</form>
<hr>

<div id="cursos">
<table class="table">
  <thead>
    <tr>
      <th scope="col">Curso</th>
      <th scope="col">Profesor</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
  <% @cursos.each do |curso| %>
    <tr>
      <th scope="row"><%= curso.nombre%></th>
      <td><%= curso.profesor%></td>
      <td class="action-container">
      <%= link_to edit_curso_path(curso), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
            <%= link_to notas_curso_path(curso), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-notepad'></i>
          <p>Notas</p>
        </div>
      <% end %>
      <%=button_to curso, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
  
</div>

<%= link_to "Nuevo curso", new_curso_path, :class=>"btn btn-dark" %> <br> <br> <br>

<%= paginate @cursos, theme: 'bootstrap-5',
    pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block" %>
    <hr>

app/views/cursos/new.html.erb
<h1>New curso</h1>

<%= render "form", curso: @curso %>

<br>

<div>
  <%= link_to "Ver lista de cursos", cursos_path, :class=>"btn btn-warning"  %>
</div>

app/views/cursos/notas.html.erb
<h4 style="margin-top: 20px;">Notas de <%= @curso.nombre %></h4>

<%= form_with url: "", method: :get do |form| %>
  <%= form.collection_select :alumno, @alumnos, :id, :nombre, { selected: params[:alumno], :include_blank => 'Todos los aumnos'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
<% end %>

<% if @notas.length > 0 %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
      <th scope="col">Nota</th>
      <th scope="col">Bimestre</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
  <% @notas.each do |nota| %>
    <tr>
      <th scope="row"><%= nota.alumno.nombre%></th>
      <td><%= nota.total%> pts</td>
      <td><%= nota.bimestre%></td>
      <td class="action-container">
      <%= link_to edit_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <% if nota.abierto? %>
      <%= link_to cierre_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bx-stop'></i>
          <p>Cerrar</p>
        </div>
      <% end %>  
      <% end %>
      <%=button_to nota, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% else %>
  <h4 style="margin: 20px 0px;">No hay notas disponibles</h4>
<% end %>

<%# Muestra el promedio %>
<div class="promedio">
<h5>Promedio:</h5>
<h5><%=number_with_precision(@sumatoria_notas, precision: 2)%> pts</h5>
</div>


<%= link_to "Crear Nota", new_nota_path(:alumno =>params[:alumno] , :curso =>@curso.id), :class=>"btn btn-dark"  %>

app/views/cursos/show.html.erb
<h5>Curso</h5>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Curso</th>
      <th scope="col">Profesor</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row"><%= @curso.nombre%></th>
      <td><%= @curso.profesor%></td>
      <td class="action-container">
      <%= link_to edit_curso_path(@curso), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <%= button_to @curso, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>

<h5>Alumnos asignados</h5>
<%= render 'cursoAlumnos' %>

<div>
  <%= link_to "Lista de cursos", cursos_path, :class=>"btn btn-warning" %>
</div>