config/routes.rb
Rails.application.routes.draw do
  resources :notas do
    member do
      post "cerrar"
      get "cierre"
    end
    collection do
      get "top10"
      get "recuperacion"
      get "download"
    end
  end
  resources :alumnos do
    member do
      get "notas"
    end
  end
  resources :cursos do
    member do
      get "notas"
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  root "home#index"

  namespace :api, defaults: {format: :json} do
    namespace :v1 do 
      devise_scope :admin do
        post "register", to: "auth#register"
        post "login", to: "auth#login"
      end
    end
  end
end

app/models/nota.rb
class Nota < ApplicationRecord
  belongs_to :curso
  belongs_to :alumno
  validates :parcial1, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 15, only_numeric: true}
  validates :parcial2, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 15, only_numeric: true}
  validates :zona, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 30, only_numeric: true}
  validates :examen, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 40, only_numeric: true}
  validates :bimestre, numericality: {greater_than_or_equal_to: 0, less_than_or_equal_to: 5, only_integer: true}
  validates_uniqueness_of :bimestre, scope: [:curso, :alumno], message: 'ya tiene nota' 


  paginates_per 2

  def self.estados
    %w(Abierto Cerrado)
  end

  def cerrado?
    self.estado_cierre == 'Cerrado'
  end

  def abierto?
    self.estado_cierre == 'Abierto'
  end
  end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  before_action :set_nota, only: %i[ show edit update destroy cierre]
  before_action :set_notas, only: %i[new, cierre]


  def cierre
    if @nota.abierto?
    
      # Calcula promedio
      # Obtiene el último binestre registrado
      @maximo_bimestre = @notas.maximum('bimestre')
      @sumatoria_notas = 0
      @promedio = 0

     for i in 1..(@maximo_bimestre)
        @nota = @notas.where(:bimestre => i)
        @sumatoria_notas = @sumatoria_notas + @nota[0].total;
        @promedio = @sumatoria_notas / i;
        @nota[0].promedio = @promedio
        @nota[0].estado_cierre = 'Cerrado'
        @nota[0].save
      end
      # Guarda calores de nota
      redirect_back(fallback_location: root_path)
    else
      redirect_back(fallback_location: root_path)
    end    
  end


  def top10
    @notas = Nota.where(:curso_id => params[:curso]).where(:bimestre => params[:bimestre]).order(promedio: :desc).limit(10)
  end


  def recuperacion
    unless params[:alumno].present? || params[:curso].present?
      @notas = Nota.where("promedio < 60")
    else
      if params[:alumno] == ""
        @notas = Nota.where(:curso_id => params[:curso]).where("promedio < 60")
      elsif params[:curso] == ""
        @notas = Nota.where(:alumno_id => params[:alumno]).where("promedio < 60")
      else
        @notas = Nota.where(:curso_id => params[:curso]).where(:alumno_id => params[:alumno]).where("promedio < 60")
      end
    end
  end


  def download
    unless params[:alumno].present? || params[:curso].present? || params[:bimestre].present?
      @notas = Nota.all
    else
      @notas = Nota.all
       params.compact_blank!

      params.each do |key, value|
        if key == "curso"
          @notas = @notas.where(:curso_id => params[:curso])
        elsif key == "alumno"
          @notas = @notas.where(:alumno_id => params[:alumno])
        elsif key == "bimestre"
          @notas = @notas.where(:bimestre => params[:bimestre])
        end
      end
    end


    # Descargar Excel
    libro = RubyXL::Workbook.new

    libro.worksheets.last.add_cell(0, 0, "Alumno")
    libro.worksheets.last.add_cell(0, 1, "Curso")
    libro.worksheets.last.add_cell(0, 2, "Nota")            
    libro.worksheets.last.add_cell(0, 3, "Bimestre")           
    libro.worksheets.last.add_cell(0, 4, "Promedio")        
    libro.worksheets.last.add_cell(0, 5, "Estado")        

    @notas.each_with_index do |nota,i|
      libro.worksheets.last.add_cell(i+1, 0, nota.alumno.nombre)
      libro.worksheets.last.add_cell(i+1, 1, nota.curso.nombre)
      libro.worksheets.last.add_cell(i+1, 2, nota.total)            
      libro.worksheets.last.add_cell(i+1, 3, nota.bimestre)            
      libro.worksheets.last.add_cell(i+1, 4, nota.promedio)    
      
      if nota.promedio < 60
        libro.worksheets.last.add_cell(i+1, 5, 'Reprobado') 
      else
        libro.worksheets.last.add_cell(i+1, 5, 'Aprobado') 

      end
    end
    

    #render json: @clientes.to_json
    send_data libro.stream.string, filename: "libro.xlsx",
                                    disposition: 'attachment'

  end
  
  
  

  # GET /notas or /notas.json
  def index
    unless params[:alumno].present? || params[:curso].present? || params[:bimestre].present?
      @notas = Nota.all.page params[:page]
    else
      @notas = Nota.all
       params.compact_blank!

      params.each do |key, value|
        if key == "curso"
          @notas = @notas.where(:curso_id => params[:curso])
        elsif key == "alumno"
          @notas = @notas.where(:alumno_id => params[:alumno])
        elsif key == "bimestre"
          @notas = @notas.where(:bimestre => params[:bimestre])
        end

      end
       @notas = @notas.page params[:page]
    end
  end

  # GET /notas/1 or /notas/1.json
  def show
  end

  # GET /notas/new
  def new
    @nota = Nota.new
    @nota.estado_cierre = 'Abierto'
  end

  # GET /notas/1/edit
  def edit
  end

  # POST /notas or /notas.json
  def create
    @nota = Nota.new(nota_params)

    @nota['total'] = nota_params['parcial1'].to_f + nota_params['parcial2'].to_f + nota_params['zona'].to_f + nota_params['examen'].to_f

    respond_to do |format|
      if @nota.save
        format.html { redirect_to nota_url(@nota), notice: "Nota was successfully created." }
        format.json { render :show, status: :created, location: @nota }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notas/1 or /notas/1.json
  def update

    @nota['total'] = nota_params['parcial1'].to_f + nota_params['parcial2'].to_f + nota_params['zona'].to_f + nota_params['examen'].to_f
    respond_to do |format|
      if @nota.update(nota_params)
        format.html { redirect_to nota_url(@nota), notice: "Nota was successfully updated." }
        format.json { render :show, status: :ok, location: @nota }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notas/1 or /notas/1.json
  def destroy
    @nota.destroy

    respond_to do |format|
      format.html { redirect_to notas_url, notice: "Nota was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nota
      @nota = Nota.find(params[:id])
    end

    def set_notas
      @notas = Nota.where(:curso_id => @nota.curso_id).where(:alumno_id => @nota.alumno_id)
    end

    # Only allow a list of trusted parameters through.
    def nota_params
      params.require(:nota).permit(:curso_id, :alumno_id, :parcial1, :parcial2, :zona, :examen, :total, :bimestre, :estado_cierre)
    end
end




class API::V1::NotasController < ApplicationController::API

end

app/helpers/notas_helper.rb
module NotasHelper
end

app/views/notas/_form.html.erb

<%= simple_form_for(@nota) do |f| %>

  <div class="form-inputs">
    <%= f.association :curso, label_method: :nombre, :selected => params[:curso], :include_blank => "Selecciona curso"%>
    <%= f.association :alumno, label_method: :nombre, :selected => params[:alumno], :include_blank => "Selecciona alumno" %>
    <%= f.input :bimestre, collection: 1..5 %>
    <%= f.input :parcial1, label: 'Parcial 1'%>
    <%= f.input :parcial2, label: 'Parcial 2' %>
    <%= f.input :zona %>
    <%= f.input :examen %>
    <%= f.input :estado_cierre, input_html: { readonly: true } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class=>"btn btn-dark", :style=>"margin-top: 10px"  %>
  </div>
<% end %>

app/views/notas/_nota.html.erb
<div id="<%= dom_id nota %>">
  <p>
    <strong>Curso:</strong>
    <%= nota.curso_id %>
  </p>

  <p>
    <strong>Alumno:</strong>
    <%= nota.alumno_id %>
  </p>

  <p>
    <strong>Parcial1:</strong>
    <%= nota.parcial1 %>
  </p>

  <p>
    <strong>Parcial2:</strong>
    <%= nota.parcial2 %>
  </p>

  <p>
    <strong>Zona:</strong>
    <%= nota.zona %>
  </p>

  <p>
    <strong>Examen:</strong>
    <%= nota.examen %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= nota.total %>
  </p>

</div>

app/views/notas/edit.html.erb
<h1>Editing nota</h1>

<%= render "form", nota: @nota %>

<br>

<div>
  <%= link_to "Ir cursos", @nota, :class=>"btn btn-warning"   %> |
  <%= link_to "Lista de cursos", notas_path, :class=>"btn btn-warning"   %>
</div>

app/views/notas/index.html.erb
<h1>Notas</h1>

<div class="btn-container">
<a href="/notas/new" class="btn btn-dark card-btn"><i class='bx bx-plus' ></i>Nueva Nota</a>
<a href="/notas/top10" class="btn btn-dark card-btn"><i class='bx bxs-trophy' ></i>Top 10 alumnos</a>
<a href="/notas/recuperacion" class="btn btn-dark card-btn"><i class='bx bx-sync' ></i>Recuperación</a>
<a href="/notas/download?curso=<%= params[:curso] %>&alumno=<%= params[:alumno]%>&bimestre=<%= params[:bimestre]%>" class="btn-green card-btn"><i class='bx bx-grid' ></i>Descargar Excel</a>
</div>


<form class="form" action="/notas" method="get">
  <%= form_with url: "", method: :get do |form| %>
    <div style="margin-top: 15px" class="row">
      <div class="form-group col-4">
        <h6>Buscar por curso</h6>
        <%= form.collection_select :curso, Curso.all, :id, :nombre, { selected: params[:curso], :include_blank => 'Selecciona un curso'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
      </div>
      <div class="form-group col-4">
        <h6>Buscar por alumno</h6>
        <%= form.collection_select :alumno, Alumno.all, :id, :nombre, { selected: params[:alumno], :include_blank => 'Selecciona un alumno'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
      </div>
      <div class="form-group col-4">
        <h6>Buscar por bimestre</h6>
        <%= form.select :bimestre, [1,2,3,4,5],  { selected: params[:bimestre], :include_blank => 'Selecciona un bimestre'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
      </div>
    </div>
  <% end %>
<div style="margin-top: 15px">
  <a href="/notas" class="btn btn-dark">Limpiar</a>
</div>
</form>

<hr>



<div id="notas">


  <table class="table">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
      <th scope="col">Curso</th>
      <th scope="col">Nota</th>
      <th scope="col">Bimestre</th>
      <th scope="col">Promedio</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
  <% @notas.each do |nota| %>
    <tr>
      <th scope="row"><%= nota.alumno.nombre%></th>
      <td><%= nota.curso.nombre%></td>
      <td><%= nota.total%></td>
      <td><%= nota.bimestre%></td>
      <td><%= nota.promedio%></td>
      <td class="action-container">
      <%= link_to edit_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <% if nota.abierto? %>
      <%= link_to cierre_nota_path(nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bx-stop'></i>
          <p>Cerrar</p>
        </div>
      <% end %>  
      <% end %>
       <%= link_to notas_alumno_path(nota.alumno, :curso => nota.curso.id), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-notepad'></i>
          <p>Notas</p>
        </div>
      <% end %>
      <%=button_to nota, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<%= paginate @notas, theme: 'bootstrap-5',
    pagination_class: "pagination-sm flex-wrap justify-content-center",
    nav_class: "d-inline-block" %>
    <hr>

app/views/notas/new.html.erb
<h1>New nota</h1>

<%= render "form", nota: @nota %>

<br>

<div>
  <%= link_to "Back to notas", notas_path, :class=>"btn btn-warning"   %>
</div>

app/views/notas/recuperacion.html.erb
<h1>Recuperación</h1>

<div class="btn-container">
<a href="/notas/new" class="btn btn-dark card-btn"><i class='bx bx-plus' ></i>Nueva Nota</a>
<a href="/notas/top10" class="btn btn-dark card-btn"><i class='bx bxs-trophy' ></i>Top 10 alumnos</a>
<a href="/notas/recuperacion" class="btn btn-dark card-btn"><i class='bx bx-sync' ></i>Recuperación</a>
</div>


    <%= form_with url: "", method: :get do |form| %>
<div style="margin-top: 15px" class="row">
        <div class="form-group col-6">
            <h6>Buscar por curso</h6>
            <%= form.collection_select :curso, Curso.all, :id, :nombre, { selected: params[:curso], :include_blank => 'Selecciona un curso'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
        </div>
        <div class="form-group col-6">
            <h6>Buscar por alumno</h6>
            <%= form.collection_select :alumno, Alumno.all, :id, :nombre, { selected: params[:alumno], :include_blank => 'Selecciona un alumno'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
        </div>
</div>
    <% end %>


    <table class="table" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
      <th scope="col">Curso</th>
      <th scope="col">Promedio</th>
      <th scope="col">Bimestre</th>
    </tr>
  </thead>

  <tbody>
  <% @notas.each do |nota| %>
    <tr>
      <th scope="row"><%= nota.alumno.nombre%></th>
      <td><%= nota.curso.nombre%></td>
      <td><%= nota.total%></td>
      <td><%= nota.bimestre%></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/notas/show.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
      <th scope="col">Curso</th>
      <th scope="col">Nota</th>
      <th scope="col">Bimestre</th>
      <th scope="col">Estado</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row"><%= @nota.alumno.nombre%></th>
      <td><%= @nota.curso.nombre%></td>
      <td><%= @nota.total%></td>
      <td><%= @nota.bimestre%></td>
      <td><%= @nota.estado_cierre%></td>
      <td class="action-container">
      <%= link_to edit_nota_path(@nota), :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-pencil'></i>
          <p>Editar</p>
        </div>
      <% end %>
      <%=button_to @nota, method: :delete, :class=>"action-link" do %>
        <div class="action-btn">
          <i class='bx bxs-trash-alt' ></i>
          <p>Borrar</p>
        </div>
      <% end %>
      </td>
    </tr>
  </tbody>
</table>


<div>
  <%= link_to "Lista de notas", notas_path, :class=>"btn btn-warning" %>
</div>

app/views/notas/top10.html.erb
<h1>Top 10 alumnos</h1>

<div class="btn-container">
<a href="/notas/new" class="btn btn-dark card-btn"><i class='bx bx-plus' ></i>Nueva Nota</a>
<a href="/notas/top10" class="btn btn-dark card-btn"><i class='bx bxs-trophy' ></i>Top 10 alumnos</a>
<a href="/notas/recuperacion" class="btn btn-dark card-btn"><i class='bx bx-sync' ></i>Recuperación</a>
</div>


    <%= form_with url: "", method: :get do |form| %>
<div style="margin-top: 15px" class="row">
        <div class="form-group col-6">
            <h6>Buscar por curso</h6>
            <%= form.collection_select :curso, Curso.all, :id, :nombre, { selected: params[:curso], :include_blank => 'Selecciona un curso'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
        </div>
        <div class="form-group col-6">
            <h6>Buscar por bimestre</h6>
            <%= form.select :bimestre, [1,2,3,4,5],  { selected: params[:bimestre], :include_blank => 'Selecciona un bimestre'}, {onchange: 'this.form.submit()', class: 'form-select'}%>
        </div>
</div>
    <% end %>



<table class="table" style="margin-top: 20px;">
  <thead>
    <tr>
      <th scope="col">Alumno</th>
      <th scope="col">Curso</th>
      <th scope="col">Promedio</th>
      <th scope="col">Bimestre</th>
    </tr>
  </thead>

  <tbody>
  <% @notas.each do |nota| %>
    <tr>
      <th scope="row"><%= nota.alumno.nombre%></th>
      <td><%= nota.curso.nombre%></td>
      <td><%= nota.total%></td>
      <td><%= nota.bimestre%></td>
    </tr>
  <% end %>
  </tbody>
</table>